body:
  - type: text
    attributes:
      name: client_id
      label: Client ID
      description: Client ID from Google Cloud Console
  - type: text
    attributes:
      name: client_secret
      label: Client Secret
      description: Client Secret from Google Cloud Console
