body:
  - type: input
    attributes:
      name: client_id
      label: 'Client ID'
      description: Client ID from Google Cloud Console
  - type: input
    attributes:
      name: project_id
      label: 'Project ID'
      description: Project ID from Google Cloud Console
  - type: input
    attributes:
      name: client_secret
      label: 'Client Secret'
      description: Client Secret from Google Cloud Console
