name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [flox]
    paths-ignore:
      - .github/workflows/*

jobs:
  publish:
    runs-on: windows-latest
    env:
      python_ver: 3.8

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "plugin.json"
          prop_path: "Version"
      - run: echo ${{steps.version.outputs.prop}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt -t ./lib
          del './lib/regex/_regex.cp39-win_amd64.pyd'
          move './temp_lib/regex/_regex.cp38-win_amd64.pyd' './lib/regex/'
          Remove-Item -Path "./temp_lib" -Force -Recurse
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'Flow.Launcher.Plugin.GoogleCalendar.zip'
          exclusions: '*.git*'
      - name: Publish
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: "Flow.Launcher.Plugin.GoogleCalendar.zip"
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
